### ISSUE TITLE
Repo needs README that credits algorithm source code

### ISSUE THREAD

**Issue by iuneee** [Ninjaman494/Hanji-Server#31]
Hi! Could you share a link to the origin of the Korean verb conj algorithms' repo by Dan Bravender?

**Comment by Ninjaman494** [comment]
Here's his [github](https://github.com/dbravender). Unfortunately, I wasn't able to find the repo. He might've made it private or deleted it entirely. In this repo, all of his code is in the `korean` folder. 

The current version is pretty modified from his original source code(made more modular, easier to maintain), but the repo at tag `v1.0.0` had code that was pretty much identical to the original source. [This link](https://github.com/Ninjaman494/Hanji-Server/tree/v1.0.0/korean) should get you the code you want, most of the conjugation related code is in `conjugator.js`.

I'm gonna leave this issue open as a reminder to myself to make a README for this repo 😅

**Comment by Ninjaman494** [comment]
Created [README](https://github.com/Ninjaman494/Hanji-Server#readme)
